#!/bin/bash
# Script to help view Render logs

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Render Logs Access Guide"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option 1: View logs via Web Dashboard (Easiest)"
echo "  1. Go to: https://dashboard.render.com"
echo "  2. Select your service (rejection-hero)"
echo "  3. Click on 'Logs' tab"
echo "  4. View real-time logs"
echo ""
echo "Option 2: Install Render CLI (via Homebrew)"
echo "  # Install Homebrew first (if not installed):"
echo "  /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "  # Then install Render CLI:"
echo "  brew install render/tap/render"
echo ""
echo "  # Authenticate:"
echo "  render login"
echo ""
echo "  # View logs:"
echo "  render services"
echo ""
echo "Option 3: Use Render API (with API key)"
echo "  Get your API key from: https://dashboard.render.com/account/api-keys"
echo "  Then you can use curl to fetch logs"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

